### ISSUE TITLE
Different JSON values

### ISSUE THREAD

**Issue by greyhoundforty** [timgws/jquery-tagcloud#1]
Just curious on what I would need to change if instead of tag and count my data is key and doc_count? I am pulling stuff from Elasticsearch and I don't have the option of changing the data I get back to match key and count that the tagcloud javascript expects. The data I am pulling looks like this 

`[{"key": "ibm_created", "doc_count": 85}]`

**Comment by greyhoundforty** [comment]
Nevermind, I discovered the $.map function in JQuery and that did the trick.

**Comment by timgws** [comment]
@greyhoundforty could you please send a sample of what you used so I can add it into the `README`?
